### ISSUE TITLE
Add installation toolbox requirements to the readme. 

### ISSUE THREAD

**Issue by ajasja** [lanceXwq/BNP-Track#2]
The GUI requires the Statistics and machine learning toolbox, which is not mentioned anywhere.

**Comment by lanceXwq** [comment]
Thanks for pointing this out! I checked the code, and it is the `poissrnd` here https://github.com/lanceXwq/BNP-Track/blob/93965c713f3d8de66e0d1f5f23203d8ec1ad8875/sampler_update_AAA.m#L23 that depends on the Statistics and machine learning toolbox.  I will soon add this point to README and doc.

**Comment by lanceXwq** [comment]
A prerequisite section has been added to the README.
